/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
          "on-secondary-fixed-variant": "#3b4951",
          "surface-container-highest": "#d3e4fe",
          "inverse-on-surface": "#eaf1ff",
          "primary-container": "#0070eb",
          "error-container": "#ffdad6",
          "inverse-surface": "#213145",
          "primary-fixed": "#d8e2ff",
          "on-surface": "#0b1c30",
          "tertiary-container": "#727577",
          "on-surface-variant": "#414755",
          "on-tertiary": "#ffffff",
          "surface-bright": "#f8f9ff",
          "on-tertiary-fixed": "#191c1e",
          "on-primary-container": "#fefcff",
          "on-tertiary-fixed-variant": "#444749",
          "outline-variant": "#c1c6d7",
          "tertiary-fixed-dim": "#c4c7c9",
          "surface-container": "#e5eeff",
          "tertiary": "#595c5e",
          "secondary": "#526069",
          "on-primary-fixed-variant": "#004493",
          "primary": "#0058bc",
          "surface-container-lowest": "#ffffff",
          "on-error-container": "#93000a",
          "secondary-fixed-dim": "#bac9d3",
          "outline": "#717786",
          "primary-fixed-dim": "#adc6ff",
          "on-tertiary-container": "#fbfdff",
          "surface-dim": "#cbdbf5",
          "on-secondary-container": "#56656e",
          "on-error": "#ffffff",
          "tertiary-fixed": "#e0e3e5",
          "inverse-primary": "#adc6ff",
          "secondary-fixed": "#d6e5ef",
          "surface-container-low": "#eff4ff",
          "on-primary": "#ffffff",
          "secondary-container": "#d3e2ed",
          "surface-variant": "#d3e4fe",
          "on-primary-fixed": "#001a41",
          "background": "#f8f9ff",
          "on-secondary": "#ffffff",
          "surface-container-high": "#dce9ff",
          "surface-tint": "#005bc1",
          "surface": "#f8f9ff",
          "on-secondary-fixed": "#0f1d25",
          "on-background": "#0b1c30",
          "error": "#ba1a1a"
      },
      "borderRadius": {
          "DEFAULT": "0.25rem",
          "lg": "0.5rem",
          "xl": "0.75rem",
          "full": "9999px"
      },
      "spacing": {
          "sm": "16px",
          "md": "24px",
          "lg": "40px",
          "margin": "24px",
          "base": "4px",
          "xl": "64px",
          "gutter": "20px",
          "xs": "8px"
      },
      "fontFamily": {
          "body-md": ["Open Sans"],
          "label-md": ["Open Sans"],
          "headline-md": ["Open Sans"],
          "body-lg": ["Open Sans"],
          "headline-lg-mobile": ["Open Sans"],
          "headline-lg": ["Open Sans"]
      },
      "fontSize": {
          "body-md": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
          "label-md": ["12px", {"lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600"}],
          "headline-md": ["20px", {"lineHeight": "28px", "fontWeight": "600"}],
          "body-lg": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
          "headline-lg-mobile": ["24px", {"lineHeight": "32px", "fontWeight": "700"}],
          "headline-lg": ["30px", {"lineHeight": "38px", "letterSpacing": "-0.02em", "fontWeight": "700"}]
      }
    },
  },
  plugins: [],
}
